export interface Product {
  id: string;
  slug: string;
  name: string;
  price: number;
  originalPrice?: number;
  category: "Clothing" | "Handcrafted" | "Utility Gear" | "Accessories";
  image: string;
  description: string;
  rating: number;
  reviews: number;
  badge?: "New" | "Sale" | "Best Seller";
  inStock: boolean;
}

export const products: Product[] = [
  {
    id: "1",
    slug: "velmora-deluxe-hoodie",
    name: "Velmora Deluxe Hoodie",
    price: 135,
    category: "Clothing",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80",
    description: "A minimalist premium hoodie made with breathable organic fabric. Designed for comfort and style in equal measure.",
    rating: 4.8,
    reviews: 124,
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "2",
    slug: "artisan-leather-utility-belt",
    name: "Artisan Leather Utility Belt",
    price: 98,
    category: "Handcrafted",
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80",
    description: "Hand-stitched belt with refined detailing and robust hardware. Each piece is unique.",
    rating: 4.7,
    reviews: 89,
    inStock: true,
  },
  {
    id: "3",
    slug: "tactical-utility-pack",
    name: "Tactical Utility Pack",
    price: 189,
    category: "Utility Gear",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    description: "Weather-resistant pack built for everyday carry and travel. 30L capacity with smart compartments.",
    rating: 4.9,
    reviews: 203,
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "4",
    slug: "charcoal-minimalist-watch",
    name: "Charcoal Minimalist Watch",
    price: 215,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    description: "Sleek timepiece with premium clasp and custom dial finish. Swiss movement.",
    rating: 4.6,
    reviews: 67,
    badge: "New",
    inStock: true,
  },
  {
    id: "5",
    slug: "premium-linen-shirt",
    name: "Premium Linen Shirt",
    price: 89,
    originalPrice: 125,
    category: "Clothing",
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80",
    description: "Lightweight linen shirt perfect for warm seasons with timeless elegance.",
    rating: 4.7,
    reviews: 156,
    badge: "Sale",
    inStock: true,
  },
  {
    id: "6",
    slug: "wool-blend-pants",
    name: "Wool Blend Pants",
    price: 165,
    category: "Clothing",
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=80",
    description: "Tailored wool-blend trousers with a refined fit for everyday wear.",
    rating: 4.9,
    reviews: 98,
    inStock: true,
  },
  {
    id: "7",
    slug: "ceramic-artisan-bowl",
    name: "Ceramic Artisan Bowl",
    price: 145,
    category: "Handcrafted",
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80",
    description: "Hand-thrown ceramic piece with unique glaze finish and rustic charm.",
    rating: 4.8,
    reviews: 44,
    badge: "New",
    inStock: true,
  },
  {
    id: "8",
    slug: "wooden-cutting-board",
    name: "Wooden Cutting Board",
    price: 85,
    category: "Handcrafted",
    image: "https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=800&q=80",
    description: "Hand-crafted wooden board with premium finish and sustainable sourcing.",
    rating: 4.6,
    reviews: 72,
    inStock: true,
  },
  {
    id: "9",
    slug: "waterproof-field-jacket",
    name: "Waterproof Field Jacket",
    price: 225,
    category: "Utility Gear",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80",
    description: "Durable weatherproof jacket designed for outdoor adventures and daily use.",
    rating: 4.9,
    reviews: 187,
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "10",
    slug: "canvas-shoulder-bag",
    name: "Canvas Shoulder Bag",
    price: 155,
    category: "Utility Gear",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80",
    description: "Versatile canvas bag with reinforced straps for daily commute and travel.",
    rating: 4.7,
    reviews: 113,
    inStock: true,
  },
  {
    id: "11",
    slug: "leather-wallet",
    name: "Premium Leather Wallet",
    price: 75,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80",
    description: "Handcrafted leather wallet with RFID protection and minimal design.",
    rating: 4.8,
    reviews: 231,
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "12",
    slug: "classic-sunglasses",
    name: "Classic Sunglasses",
    price: 135,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80",
    description: "Timeless sunglasses with UV protection and elegant frame design.",
    rating: 4.8,
    reviews: 95,
    inStock: true,
  },
  {
    id: "13",
    slug: "merino-crewneck",
    name: "Merino Crewneck Sweater",
    price: 145,
    category: "Clothing",
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80",
    description: "Ultra-soft merino wool crewneck with a relaxed fit. Perfect for layering.",
    rating: 4.9,
    reviews: 78,
    badge: "New",
    inStock: true,
  },
  {
    id: "14",
    slug: "leather-crossbody",
    name: "Leather Crossbody Bag",
    price: 195,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80",
    description: "Full-grain leather crossbody with adjustable strap and brass hardware.",
    rating: 4.7,
    reviews: 62,
    inStock: true,
  },
  {
    id: "15",
    slug: "handmade-ceramic-mug",
    name: "Handmade Ceramic Mug",
    price: 55,
    category: "Handcrafted",
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80",
    description: "Each mug is individually thrown and glazed — no two are exactly alike.",
    rating: 4.9,
    reviews: 189,
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "16",
    slug: "trail-running-vest",
    name: "Trail Running Vest",
    price: 175,
    category: "Utility Gear",
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=800&q=80",
    description: "Lightweight hydration vest with multiple pockets for long-distance runs.",
    rating: 4.8,
    reviews: 54,
    inStock: true,
  },
];
